### ISSUE TITLE
Please support older versions of Rust

### ISSUE THREAD

**Issue by joshtriplett** [brson/error-chain#101]
I'd like to use error-chain as part of the dependencies for a project, but that project needs to support Rust 1.10.  error-chain uses the ability to put attributes on non-item statements and expressions, specifically to handle the backtrace feature.  Please consider moving those attributes upward (even though it duplicates a bit more code), to allow error-chain to build and run on Rust 1.10.

**Comment by joshtriplett** [comment]
Currently working on a patch for this.

**Comment by Yamakaky** [comment]
Cool!

**Comment by joshtriplett** [comment]
Mostly there; ran into what seems like a bug in `#[derive(Debug)]` in Rust 1.10. Trying to debug Debug.

**Comment by joshtriplett** [comment]
I think I ran into https://github.com/rust-lang/rust/issues/22250 , fixed in Rust 1.11.

**Comment by joshtriplett** [comment]
https://github.com/brson/error-chain/pull/103 fixes this enough for some use cases.  I don't see any obvious way to get backtrace working without statement blocks, and I don't want to add a pile of conditionals to make a subset of the tests work (avoiding all tests that use `#[cfg(...)]` on variants within `error_chain!`), but the crate itself works perfectly with #103.

**Comment by joshtriplett** [comment]
Thanks for all the quick response on #103. As soon as a new version of error-chain appears on crates.io with this fixed, I'll update metadeps to use it.

**Comment by Yamakaky** [comment]
0.7.2 released.
