### ISSUE TITLE
Comment in error_chain foreign_links example was not updated along with code.

### ISSUE THREAD

**Issue by nelsonjchen** [brson/error-chain#106]
https://github.com/brson/error-chain/commit/bce3d9900ec4c74df06cfa9838cebfb6cab84231#diff-b4aea3e418ccdb71239b96952d9cddb6L137

This example shows up in the first page of the documentation currently here: 

https://brson.github.io/error-chain/error_chain/index.html#declaring-error-types

The comment "In this case, it will e.g. generate an `ErrorKind` variant called `Dist` which in turn contains the `rustup_dist::ErrorKind`, with conversions from `rustup_dist::Error`. " refers to the example foreign link below which used to use an example from rustup but is now referring to some example that's a bit more generic and no longer involves `rustup_dist`.

I'm still trying to grasp `error-chain` so I'm not sure what is supposed to be there.

**Comment by nelsonjchen** [comment]
The `foreign_links` section looks odd too. I don't think its talking about `Temp` anymore.

**Comment by Yamakaky** [comment]
Yeah, you are right.
