### ISSUE TITLE
question: how to chain an io::Error ?

### ISSUE THREAD

**Issue by little-dude** [brson/error-chain#112]
Hi,

This is more a question than an issue. From reading the docs, I don't really understand how to chain errors from other crates, use `foreign_links`. Here, I'm trying to chain an `io::Error`, but this example fails to compile with a rather cryptic error. Here is the code:

```rust
#![recursion_limit = "1024"]
#[macro_use]
extern crate error_chain;

use std::net::{TcpListener, TcpStream, SocketAddrV4};
use std::time::Duration;

mod errors {
    use std::io;
    error_chain! {
        foreign_links {
            Io(io::Error);
        }

        errors {
            ConnectionFailed {
                description("Connection failed")
                display("Connection failed")
            }
        }

    }
}

use errors::*;

fn main() {
    if let Err(ref e) = run() {
        println!("error: {}", e);
        for e in e.iter().skip(1) {
            println!("    caused by: {}", e);
        }
        if let Some(backtrace) = e.backtrace() {
            println!("backtrace: {:?}", backtrace);
        }
        std::process::exit(1);
    }
}

fn run() -> Result<()> {
    let stream = connect()?;
    // do tcp stuff 
    Ok(())
}

fn connect() -> Result<TcpStream> {
    let mut stream = TcpStream::connect("127.0.0.1:500").chain_err(|| ErrorKind::ConnectionFailed.into())?;
    stream.set_read_timeout(Some(Duration::from_millis(100))).chain_err(|| ErrorKind::ConnectionFailed.into())?;
    stream.set_write_timeout(Some(Duration::from_millis(100))).chain_err(|| ErrorKind::ConnectionFailed.into())?;
    Ok((stream))
}
```

Now the error:

```
error[E0282]: unable to infer enough type information about `EK`
  --> src/main.rs:47:58
   |
47 |     let mut stream = TcpStream::connect("127.0.0.1:500").chain_err(|| ErrorKind::ConnectionFailed.into())?;
   |                                                          ^^^^^^^^^ cannot infer type for `EK`
   |
   = note: type annotations or generic parameter binding required
```

Am I trying to do some non-sense, here?

**Comment by Yamakaky** [comment]
- Try the `quick_main` macro ;)
- you don't need `ErroKind::Variant.into()`, you can just return `ErrorKind::Variant`. The closure must returns an `Into<ErrorKind>`,  but you do something like returning `Into<Into<ErrorKind>>`, so the compiler doesn't know what's the type should be after the first `into()` 
- If you use `error_chain`, you don't need `foreign_error`

**Comment by little-dude** [comment]
Thanks @Yamakaky !

- `quick_main` is pretty cool, adopted!
- removing `into()` does fix my problem.
- I don't understand your third point. But that's because I don't really understand that `foreign_error`/`foreign_links` are.

**Comment by Yamakaky** [comment]
Mostly, your `foreign_error` just adds an `impl From<io::Error> for Error`.

**Comment by little-dude** [comment]
All right. Simple enough. Thanks a lot :) I'm closing this.
