### ISSUE TITLE
add function/method for easily printing errors

### ISSUE THREAD

**Issue by vitiral** [brson/error-chain#115]
it is probably good for library authors to have control of what their errors will look like to their users, but when debugging it would nice to just call `error.display()` or something (similar to `Path`) to get the full detailed display of the error (included causes) without having to write it custom for every lib.

If you support this idea, I would be happy to code it up.

Thanks for the great lib

**Comment by Yamakaky** [comment]
https://docs.rs/error-chain/0.8.1/error_chain/trait.ChainedError.html#method.display ;)

**Comment by vitiral** [comment]
@Yamakaky wow, it exists! I couldn't find it in the docs.

Is it possible this could be highlighted better in the README? The way the template is given to users makes me think that's the only way to display that information.

It's totally possible I'm just daft though :)

**Comment by Yamakaky** [comment]
Sure, how would you do it?
