### ISSUE TITLE
error[E0308]: mismatched types: expected struct `errors::Error`, found struct `std::io::Error`

### ISSUE THREAD

**Issue by mre** [brson/error-chain#119]
`error_chain!` looks really well-designed.
While testing it I ran into a nasty error.
It must be something trivial with my code but it seems like I'm missing a piece of the puzzle.

Here's a minimal example:

```Rust
#[macro_use]
extern crate error_chain;

mod errors {
    error_chain! {
		foreign_links {
		   IoError(::std::io::Error);
    	}
	}
}

use errors::*;
use std::process::Output;
use std::process::Command;

fn failing() -> Result<Output> {
	Command::new("ls")
		.arg("-l")
		.output()
}

fn main() {
	failing();
}
```

When trying to run the above code, I get the following error message:

```Rust
error[E0308]: mismatched types
  --> src/main.rs:17:2
   |
17 | 	Command::new("ls")
   | 	^ expected struct `errors::Error`, found struct `std::io::Error`
   |
   = note: expected type `std::result::Result<std::process::Output, errors::Error>`
   = note:    found type `std::result::Result<std::process::Output, std::io::Error>`

error: aborting due to previous error

error: Could not compile `error_chain_test`.
```

Probably something regarding implicit `From` conversion between `std::io::Error` and my own `Error` type. Does anybody see my mistake?

**Comment by Yamakaky** [comment]
You have to convert the error from io::Error to Error.
```rust
Ok(Command...?)
```
should do the trick.

**Comment by mre** [comment]
Yes indeed that did the trick! This is awesome. Thanks @Yamakaky 😀

**Comment by hasufell** [comment]
I think there should be a macro/Function for this, since this is quite annoying. I did something like this (not very good with writing such generic trait code yet, though):

```rust
pub trait ToErr {
    type Item;
    fn cerr(self) -> Result<Self::Item>;
}

impl<A, E: std::error::Error> ToErr for std::result::Result<A, E>
        where Error: std::convert::From<E> {
    type Item = A;
    fn cerr(self) -> Result<Self::Item> {
        return self.map_err(From::from);
    }
}
```

Then you would do:

```rust
fn failing() -> Result<Output> {
	Command::new("ls")
		.arg("-l")
		.output()
                .cerr();
}
```

**Comment by Yamakaky** [comment]
I think you should be able to add it to [ResultExt](https://github.com/brson/error-chain/blob/master/src/error_chain.rs#L302-L324). Do you want to try a PR?

**Comment by hasufell** [comment]
I can give it a try
