### ISSUE TITLE
the trait bound `errors::Error: std::convert::From<duct::Error>` is not satisfied

### ISSUE THREAD

**Issue by mre** [brson/error-chain#120]
Probably another trivial error similar to #119, but I can't come up with a fix.

Cargo.toml:
```
[dependencies]
duct = "0.5.1"
error-chain = "0.7.2"
```

src/main.rs:

```Rust
#[macro_use]
extern crate error_chain;

#[macro_use]
extern crate duct;

use std::process::Output;

mod errors {
    use duct;

    error_chain! {
         links {
             ShellError(duct::Error, duct::ErrorKind);
         }
    }
}

use errors::*;

fn failing() -> Result<Output> {
	Ok(cmd!("ls -l").stdout_capture().run()?)
}

fn main() {
	failing();
}

```

Output:
```Rust
error[E0412]: type name `duct::ErrorKind` is undefined or not in scope
  --> src/main.rs:13:5
   |
13 |     error_chain! {
   |     ^ undefined or not in scope
   |
```

As you can see, this example is using duct.rs which also recently switched to error-chain.
I'm confused why `duct::ErrorKind` is not exposed from duct.rs. From the source code it looks like it's using error-chain in a straightforward way:
https://github.com/oconnor663/duct.rs/blob/master/src/lib.rs#L1295

What am I missing here? 😉

**Comment by Yamakaky** [comment]
Hum...

**Comment by oconnor663** [comment]
I think the issue here is that duct's use of `error_chain` is in master but not in v0.5.1. I added it pretty recently, and I haven't done another release since then.

**Comment by Yamakaky** [comment]
ahah

**Comment by mre** [comment]
Jup, @oconnor663 is right. Will build against master until a new release is out. Thanks you two! 👍  Closing.
