### ISSUE TITLE
Clonable errors

### ISSUE THREAD

**Issue by jugglerchris** [brson/error-chain#121]
I have an application where it would be handy to be able to clone the `Error` type declared by`error_chain!()`.  Is there (or could there be) a way to add a `#[derive(Clone)]`?

**Comment by Yamakaky** [comment]
Hum, we have the same thing for Sync, Eq... Maybe allow the user to declare the exact types he wants? What do you think?

**Comment by jugglerchris** [comment]
Yes, that sounds useful.

**Comment by Yamakaky** [comment]
Idea about the syntax changes? Maybe adding a new block type like `foreign_errors` or `links`, with a default to Sync + Send so that it's backward compatible.

**Comment by jugglerchris** [comment]
My first thought would be allowing an actual `#[derive(Clone,Sync)]` before the `errors { ... }` block; I haven't looked into how easy (if at all) that would be to implement in the macro.  A new block type would fit in with other `error-chain` syntax though, so I'm not really fussed either way personally.  :-)

**Comment by Yamakaky** [comment]
I starting looking about how to make the change. There is two troubles:
1) `State` is crate-level, so we can't modify it for each error. We could make it generic but
2) Rust doesn't allow us to do things like `Box<Error + Debug>`, `Sync` and `Send` being special cases.
I think we have to generate an empty trait per Error, add the desired traits as dependencies and implement it for each struct that implements all the dependencies. Something like
```rust
trait Trait: Debug + Sync + Clone {}
impl<T: Debug + Sync + Clone> Trait for T {}
```
What do you think?

**Comment by Yamakaky** [comment]
Apparently, `Clone` is not object safe, so we can't add it as a dependency like above. The rest works though: https://play.rust-lang.org/?gist=7c05d66e1e017248fb61162b4c9aea92&version=stable&backtrace=1

**Comment by jugglerchris** [comment]
I discovered the `Clone` problem when trying to implement it manually as a workaround.  I guess I'll have to think again!

**Comment by Yamakaky** [comment]
Closing for https://github.com/brson/error-chain/issues/134
