### ISSUE TITLE
Is there a way to construct `Error` that is chained directly, without calling `chain_err`?

### ISSUE THREAD

**Issue by golddranks** [brson/error-chain#125]
I'm trying to converge on a modern version of error-chain with my project (used a fork for a while). In some situations I need to construct an `Error` value, and I want to chain another version as the cause of it, but the `.chain_err()` API is inconvenient in this case because it requires me to have the `Error` value inside a `Result`.

There was briefly an API called `.caused_err()` that allowed to create a chained error without it being wrapped inside a `Result`, but that was axed because of inference regressions, I think.

Is there currently a way to build directly an `Error` value chained from another error?

**Comment by golddranks** [comment]
This kind of situation arises often when one wants to handle an error case early and wrap that again for later further handling, so one uses `map_err`, match on the error, and then return different ErrorKinds depending on the error. The problem is that currently there seems to be no good ways to construct a chained `Error` inside the `map_err`.  One has to wrap the `Error` inside an `Result::Err()`, call the `chain_err()` on that and then unwrap. This is tedious and ugly.

**Comment by golddranks** [comment]
Since the older, trait-based API caused inference issues (I think some of those were due to bugs in the inference algo, but some might have been legit), it might make sense to have a simple constructor on `Error`, like `Error::from_err(error, kind)`. That would create an `Error` from `kind`, and chain `error` as the cause.

**Comment by golddranks** [comment]
Sent a PR: https://github.com/brson/error-chain/pull/126

**Comment by luser** [comment]
I ran into this same thing when refactoring some existing code to use error-chain. The most noticeable place I saw it was when using `io::Error::last_os_error()` after calling system functions via FFI, like here:
https://github.com/luser/sccache/blob/4aabbfcc8c82a98d1c162c9bc749d3dde81de4dc/src/commands.rs#L287

I punted on doing the right thing there because I couldn't figure out how to make it work properly.

**Comment by golddranks** [comment]
I'll try to get the PR in later today!

**Comment by aldanor** [comment]
Should this get closed now?

**Comment by Yamakaky** [comment]
Yeah, sure
