### ISSUE TITLE
release: please push corresponding git tag

### ISSUE THREAD

**Issue by lucab** [brson/error-chain#128]
It looks like error-chain used to have git tags for every uploaded crate, but the last one is currently 0.7.1 while crates.io has 0.9.0.

Please push corresponding git tags for new crates.io releases, as it makes history-digging easier while looking at the git repo.

**Comment by Yamakaky** [comment]
Oops, doing that now

**Comment by Yamakaky** [comment]
They where created, I just forgot to push them ^^
