### ISSUE TITLE
Optional `futures` integration

### ISSUE THREAD

**Issue by alexcrichton** [brson/error-chain#130]
When integrating `error-chain` into `sccache` (https://github.com/mozilla/sccache/pull/70) I ended up adding a [small helper](https://github.com/alexcrichton/sccache/blob/74eda9dfb905e287d99a0c424b2208a6d4806301/src/errors.rs#L39-L55) for adding the `chain_err` method to futures as well. Perhaps this crate itself could have an optional feature to enable this?

**Comment by luser** [comment]
There was https://github.com/brson/error-chain/issues/90 already filed, but that code you wrote would be a good basis for a patch here.

**Comment by alexcrichton** [comment]
Oops! I'll close in favor of that
