### ISSUE TITLE
Regression with type inference in a recent nightly affects bail!

### ISSUE THREAD

**Issue by golddranks** [brson/error-chain#132]
One of the doc tests fails.

The breakage happens between nightlies `668864d9e 2017-02-16` and `536a900c4 2017-02-17`.

**Comment by Yamakaky** [comment]
Thanks!

For the record, the error is https://travis-ci.org/brson/error-chain/jobs/203564573#L385, with [this line](https://github.com/brson/error-chain/blob/master/src/lib.rs#L238) causing problem. Maybe it's because the `Ok(())` is unreachable?

**Comment by Emilgardis** [comment]
I'm getting this also in recent nightly, but in code that previously worked.
`Result<()>` seems to be the problem.

**Comment by Yamakaky** [comment]
What do you mean?

**Comment by Emilgardis** [comment]
I had an unreachable `Ok(())`, replacing it with `unreachable!` fixed it.

**Comment by Yamakaky** [comment]
Yeah, it's an inference change from the compiler.
