### ISSUE TITLE
Please include the two licenses in the top level of the repository

### ISSUE THREAD

**Issue by vishvananda** [brson/error-chain#142]
Generally, the license text needs to be included in the repository. Would it be possible to include LICENSE-APACHE and LICENSE-MIT in the repository?

**Comment by Yamakaky** [comment]
Right. Do you want to do it?

**Comment by vishvananda** [comment]
done @  https://github.com/brson/error-chain/pull/143

**Comment by est31** [comment]
Can be closed now
