### ISSUE TITLE
chain_err() metod for E: Error + Send + 'static ?

### ISSUE THREAD

**Issue by kgv** [brson/error-chain#147]
What about impl `chain_err()` metod for `E: Error + Send + 'static`?
Maybe use trait `ErrorExt`?

**Comment by Yamakaky** [comment]
You already have https://docs.rs/error-chain/0.10.0/error_chain/trait.ChainedError.html#tymethod.with_chain.

**Comment by kgv** [comment]
I mean using `error.chain_err(|| ErrorKind::Test)` similarly `result.chain_err(|| ErrorKind::Test)`.
For example:

Now it:
```rust
open_file().map_err(|err| Error::with_chain(err, ErrorKind::Test))
```

What i mean:
```rust
open_file().map_err(|err| err.chain_err(|| ErrorKind::Test))
```

I think that the second case is more concise.

**Comment by Yamakaky** [comment]
Why not. Do you want to try a PR?

**Comment by kgv** [comment]
Ok, i will try PR

**Comment by kgv** [comment]
I implement it.
https://github.com/kgv/error-chain/tree/chain_err_for_error

But now I think that this is not such a good idea: it breaks backward compatibility for all cases wich impl custom type names:
```rust
 types {
          // MyError, MyErrorKind, MyErrorExt, MyResultExt; // <- New 
         MyError, MyErrorKind, MyResultExt; // <- Old
}
```

Are there any ideas for implementing with backward compatibility?

**Comment by Yamakaky** [comment]
Yeah, that's why I didn't do it if I remember correctly ^^
