### ISSUE TITLE
Documentation for the `bail!` macro is misleading and confusing

### ISSUE THREAD

**Issue by dead10ck** [brson/error-chain#148]
The top-level crate documentation has a section for the `bail!` macro that currently reads:

> Instead we can use the `bail!` macro, which, much like `try!` and `?`, performs an early return with conversions.

This isn't really correct. `try!` and `?` operate on a `Result` type, returning the `Ok` value, if it is `Ok`, or returning early from the function if it is an `Err`. `bail!` is equivalent to just returning an `Err`, period. I didn't understand the examples until I actually looked at the `bail` module documentation and the source code of the `bail!` macro, just to be sure.

**Comment by Yamakaky** [comment]
Right. As you did some research work, do you want to do a PR to improve the doc?

**Comment by dead10ck** [comment]
Yeah, sure; I'll submit a PR when I have a free moment :)
