### ISSUE TITLE
Adding a new OptionExt trait?

### ISSUE THREAD

**Issue by dgrnbrg** [brson/error-chain#151]
Hello, I'm interested in contributing a new Ext trait for Option, so that I can have `chain_err` on options when they're `None`. Often in my code I am working with a vector or iterator that should have a certain number of elements, and I want to bail when that's not the case. Currently, I have tons of `option.ok_or(Error::from(format!("problem because of {:?}", context)))?` throughout my code, and I think it'd be cool to be able to instead do: `option.chain_err(|| format!("problem beause of {:?}", context))`. That way, I wouldn't need to compute the error in the success case, and I'd delegate the error casting to type inference. Would you accept this as a PR?

**Comment by Yamakaky** [comment]
Yes! Though, could you first try to `impl ResultExt for Option`? I think it should be good.

**Comment by dgrnbrg** [comment]
[Here's my first draft at the feature](https://github.com/dgrnbrg/error-chain/commit/eb159adadedb2096d459864d29ad19696a75f72a)--I still need to write tests, and try integrating it throughout my code. Does that look good to you WRT to how I used `State`?

**Comment by Yamakaky** [comment]
You can use `from_kind` which creates a default state for you.

**Comment by dgrnbrg** [comment]
So, you're saying to use `$crate::Error::from_kind(callback().into())`, rather than making a new `ChainedError` with default `State`?

**Comment by Yamakaky** [comment]
Yes, that's it.

**Comment by dgrnbrg** [comment]
Here's my updated changes: https://github.com/dgrnbrg/error-chain/commit/d02131ff6956ef1ec44eaefe7cd297ecdc14ab36

I'm using `from_kind` like you suggested, and I've also had to remove the `E` type from `ResultExt`, since it turns out `ResultExt` doesn't ever actually need to be parameterized on `E`, and it's impossible to determine when chaining with an `Option<T>`.

I've also included a new method `ChainedError::with_boxed_chain`, to create a way to start with a boxed `Error` trait object and get the crate's concrete type of `Error` with the boxed error as context.

Finally, you can see the commented out code I wrote which would allow for `chain_err` to be invoked on a boxed error, as I wrote about in #152, if you have any thoughts on how to get the compiler to accept it.

**Comment by Yamakaky** [comment]
Sorry for the delay.

Seems nice. Could you open a PR?

**Comment by dgrnbrg** [comment]
I'm closing this in favor of the corresponding PR #156.
