### ISSUE TITLE
Doc comments on links

### ISSUE THREAD

**Issue by kw217** [brson/error-chain#153]
The current `error_chain!` macro permits doc comments on errors, but not on links:
```rust
    error_chain!{
        links {
            /// Doc comment for links
            LinkedError(super::databases::Error, super::databases::ErrorKind);
        }
    }
```
yields
```rust
error: expected ident, found #
  --> src/lib.rs:11:13
   |
11 |             /// Doc comment for links
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^
```
whereas doing similarly for an error in `errors` works just fine.

See a full failing example [here](https://gist.github.com/kw217/feecc37fd70b4700a348715c1912efc3) - if line 11 is a normal comment, the compiler emits a warning; if it's a doc comment, it fails.

**Comment by Yamakaky** [comment]
Yeah I know, see https://github.com/brson/error-chain/issues/63 (the comments are converted to the `#[doc = ...]` form. If you find a working solution, I take it!

**Comment by kw217** [comment]
Thanks, sorry for duplicating!
