### ISSUE TITLE
Traits returning chained errors without exposing impl details

### ISSUE THREAD

**Issue by nmusatti** [brson/error-chain#155]
First off I have to say that I'm an absolute Rust beginner, and even more so with error-chain.
I was looking for a way to let a trait impose error-chain based error handling without having to know or expose details about its implementations' error management. I came up with a solution that uses the `Error::with_chain()` method and I wanted to know if it is a reasonable approach or if it could be simplified in any way.
Here's an example of how I could define my trait:
```rust
mod my_trait {
  error_chain! {
    errors { MyTraitError }
  }

  pub trait MyTrait {
    fn may_fail(& self) -> Result<i32>;
  }
}
```
`MyTraitError` is the `ErrorKind` variant of all the implementation errors.
In another module/crate I define a `MyImpl` type:
```rust
pub struct MyImpl { pub i : i32 }

impl MyImpl {
  pub fn fails(&self) -> Result<()> { bail!("fails!"); }
}
```
This is how I would implement my trait:
```rust
impl my_trait::MyTrait for MyImpl {
  fn may_fail(& self) -> my_trait::Result<i32> {
    match self.fails().chain_err(||"may fail") {
      Err(e) => Err(my_trait::Error::with_chain(e, my_trait::ErrorKind::MyTraitError)),
      Ok(_) => Ok(self.i)
    }
  }
}
```
Given this `main()` function:
```rust
fn main() {
  use std::process::exit;

  let mt : Box<my_trait::MyTrait> = Box::new(my_impl::MyImpl{ i: 42 });
  let t = mt.may_fail();
  if let Err(e) = t  {
    println!("error: {}", e);
    for e in e.iter().skip(1) {
      println!("caused by: {}", e);
    }
    exit(1);
  }
  println!("Value: {}", t.unwrap());
}
```
The output is:
```
error: MyTraitError
caused by: may fail
caused by: fails!
```

**Comment by Yamakaky** [comment]
I don't really understand what you want to do. Could you show the expected output with and without the fix?

**Comment by nmusatti** [comment]
First of all, just to be clear: mine is just a question on the proper use of error-chain, I don't intend to propose any changes. As I said, I'd like my traits to impose error-chain error handling, but a trait cannot be aware of all the kinds of errors that its implementors may have to handle. For this reason I cannot use links. Still I would like my trait implementors to hook their errors to the trait error chain and I was wondering how to do that.
The example above is contrived, it is meant to always fail. What I wanted to show is that by using the Error::with_chain() method I can still hook my errors to the trait error and I was wondering if this is a reasonable thing to do. Obviously I won't be able to match on my implementation errors, but at least I won't lose information on the original cause of my error. Hope I've been clearer this time.

**Comment by Yamakaky** [comment]
Yeah, with_chain should be good. It's a Box<Error> inside, so you can't pattern match. Is that's OK, it's perfectly fine.

**Comment by nmusatti** [comment]
Well, you can't have abstraction and the details too, can you? Thank you!
