### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by brson** [brson/error-chain#177]
Start adding changelogs before releases. See https://github.com/rust-lang-nursery/rustup.rs/blob/master/CHANGELOG.md for one possible format.

This probably needs to be done by a maintainer.

**Comment by Yamakaky** [comment]
https://github.com/brson/error-chain/blob/master/CHANGELOG.md ?

**Comment by ahmedcharles** [comment]
This seems to be complete?

**Comment by Yamakaky** [comment]
Yeah, I guess
