### ISSUE TITLE
infer the `ErrorKind` - e.g. via an associated type of some trait :-)

### ISSUE THREAD

**Issue by colin-kiegel** [brson/error-chain#32]
# Motivation

I think one could simplify the link definitions:

```
    links {
        rustup_dist::Error, rustup_dist::ErrorKind, Dist;
    }
```

to something like this

```
    links {
        rustup_dist::Error, Dist;
    }
```
## Possible Solution

To achieve this, `rustup_dist::Error` could implement something like `trait ErrorChain { type ErrorKind: StdError + Debug; }`. If this trait is in scope, the associated type could be queried via `rustup_dist::Error::ErrorKind` and does not need to be set explicitly. I think this would allow a more comfortable API.
## Drawbacks
- There is already a `ChainErr` trait. A similar named trait could lead to some confusion.
## Alternative

Alternatively, the compound error could just be a type-alias for a specific variant of a generic struct. I.e. 
- macro defines `pub enum $error_kind_name { /* ... */ }`
- macro also defines `type $error_name = ErrorChain<$error_kind_name>;`
- the `error-chain` crates defines the generic struct `pub struct ErrorChain<ErrorKind: StdError + Debug> ( /* ... */ );`

The effect should roughly be the same - the link definition would then include the ErrorKind instead.

```
    links {
        rustup_dist::ErrorKind, Dist;
    }
```

**Comment by brson** [comment]
Sounds like a good idea to me. The trait would live (unlike most of the code for error-chain) directly in the error-chain crate, not generated by the macro. So the error-chain macro can find the trait with `$crate`.

Alternate names might be `LinkedError`, `ErrorLink`, `ChainedError`. I agree `ErrorChain` is confusing.
