### ISSUE TITLE
Does this library allocate?

### ISSUE THREAD

**Issue by nathanaeljones** [brson/error-chain#37]
I'm wondering if this is suitable for representing errors in a potential out-of-memory condition (i.e. malloc failure)?

**Comment by brson** [comment]
Yes, this library allocates in the `chain_err` method. Putting the "chained errors" into boxes on the heap is one of the primary tradeoffs it makes.

**Comment by nathanaeljones** [comment]
Would there be any way to create or mark an error to prevent allocations? I.e, if I'm manually handling OOM conditions, but want to represent the result as an Error, can I do so without allocs?

**Comment by Yamakaky** [comment]
Closing for #64

**Comment by nathanaeljones** [comment]
My use case is runtime-based, i.e, I'd like chain_error functionality *except* for one class of origin error. I think the compile-time feature is awesome, though.

I should probably private-fork error_chain given the particular requirements of my lib and try to figure out a way to make this work. Thanks for the feedback!

**Comment by Yamakaky** [comment]
It could help others. Do you have any idea how we should change the syntax?

**Comment by nathanaeljones** [comment]
I haven't done any exploratory work, no. I'm a few days off from refactoring error handling in my lib.
