### ISSUE TITLE
Confusion/ergonomics problem with type inference and try!() or ?

### ISSUE THREAD

**Issue by golddranks** [brson/error-chain#39]
Sometimes I want not to chain errors, but _replace_ an error with another (in this case I don't want to leak information of what caused the AuthError). Trying to use map_err() for this, I run into problems with type inference.

```
pub fn auth_user(conn : &PgConnection, email : &str, plaintext_pw : &str) -> Result<User> {
    let (user, hashed_pw_from_db) = get_user_pass_by_email(conn, email)
                                .map_err(|_| ErrorKind::AuthError.into())?;
    let _ = password::check_password(plaintext_pw, hashed_pw_from_db.into())
                                .map_err(|_| ErrorKind::AuthError.into())?;
    Ok(user)
```

with code like this, I suspect that the type inference is not decidable:

```
error[E0282]: unable to infer enough type information about `_`
   --> src/lib.rs:140:37
    |
140 |     let (user, hashed_pw_from_db) = get_user_pass_by_email(conn, email)
    |                                     ^ cannot infer type for `_`
    |
    = note: type annotations or generic parameter binding required
```

I think this is because this code contains two nested `.into()`s, ErrorKind → Error, and then inside the `?` operator. With two `.into()`, the types contain too much degrees of freedom to be inferable.

It's maybe because I'm a newbie, but it took me a LOT of fumbling to get the type annotations right:

```
pub fn auth_user(conn : &PgConnection, email : &str, plaintext_pw : &str) -> Result<User> {
    let (user, hashed_pw_from_db) = get_user_pass_by_email(conn, email)
                                .map_err::<Error, _>(|_| ErrorKind::AuthError.into())?;
    let _ = password::check_password(plaintext_pw, hashed_pw_from_db.into())
                                .map_err::<Error, _>(|_| ErrorKind::AuthError.into())?;
    Ok(user)
}
```

Then it occurred to me that since `.into()`ing ErrorKind → Error is a SUPER-common operation in `error_chain`, it would benefit the type inference if there were a _non-generic_ function to do just that. I think it would help the type inference in many situations where more than one `.into()` would make the inference undecidable.

**Comment by brson** [comment]
Yes, this is a bad case for error-chain, and in general one of the problems with the library is you must know how to get around inference failures.

In this case I would have written `map_err(|_| Error::from(ErrorKind::AuthError))` (this is generally a solution when `Into` conversions fail). The documentation should mention this case. Does that work for you?

**Comment by golddranks** [comment]
Yes, that seem to work. Thank you. I think I still would use a non-generic into if that were available. Let me continue in another thread.
