### ISSUE TITLE
Another usability issue with map_err

### ISSUE THREAD

**Issue by golddranks** [brson/error-chain#40]
Sometimes I want not just chain errors, but "semi-handle" them: check the result, maybe handle or "decorate" _one_ possible error and still pass the`Result` downstream.

`.map_err()` allows me to inspect the error, have my way with it and then continue, but the API of `error_chain` could do a lot better to help with this. Here's the problem: it seems that you can only chain errors (box and store the earlier error as the cause) with `.chain_err`, and that only works with `Result`s. But inside a `.map_err()` we are dealing directly with some error values. This leads to this monstrosity, where I first match on the foreign `ErrorKind`, then wrap it _again_ in an `Result::Err` variant (+ work around inference issues), pass that to the `chain_err()` and then unwrap that to return from the `.map_err()`.

```
users::table
    .inner_join(passwords::table)
    .filter(users::email.eq(user_email))
    .first(&*conn)
    .map_err(|e| match e {
            e @ NotFound => Err::<(), diesel::result::Error>(e).chain_err(|| ErrorKind::NoSuchUser(user_email.into())).unwrap_err(),
            e => Err::<(), diesel::result::Error>(e).chain_err(|| "Error when trying to retrieve user!").unwrap_err(),
    })
```

If there were a version of `chain_err()` that worked directly with values, not with `Result` containers, it would help a lot:

```
users::table
    .inner_join(passwords::table)
    .filter(users::email.eq(user_email))
    .first(&*conn)
    .map_err(|e| match e {
            e @ NotFound => e.caused_err(|| ErrorKind::NoSuchUser(user_email.into())),
            e => e.caused_err(|| "Error when trying to retrieve user!"),
    })
```

Am I missing something really obvious or does this make sense?

**Comment by golddranks** [comment]
So, I tried and made two additional APIs. My work is here:  https://github.com/golddranks/error-chain/commit/76d5ccfa6063d6d958dad3d2030116be2431ac8b

I added a CausedErr trait that is analogous to ChainErr, but works directly on types implementing the `std::error::Error` trait, not `Result`. With that, I was able to get the ugly
```
e => Err::<(), diesel::result::Error>(e).chain_err(|| "Error when trying to retrieve user!").unwrap_err(),
```
row to 
```
e => e.caused_err(|| "Error when trying to retrieve user!"),
```

I could also refactor the implementation of ChainErr to use that. (Just basic DRY)

I also added a `.to_err()` helper method for `ErrorKind`, which works exactly like `.into()` but causes less problems with type inference. (Basically it's but a sugar to `Error::from()`, but I like the conciseness, method syntax and lack of `::` better.)

Still WIP in the sense that I haven't touched the docs. But what do you think about these changes? Do they seem worthwile, @brson ? Shall I send a PR?

**Comment by Yamakaky** [comment]
It seems close to `cause()` from https://github.com/tailhook/quick-error?

**Comment by Yamakaky** [comment]
@golddranks please review https://github.com/brson/error-chain/pull/62

**Comment by TedDriggs** [comment]
I see the PR for this has stalled due to an inference problem; are there any plans to revive it?

FWIW, I hit the exact same issue (also when using `map_err`) and found that this was sufficient to get moving again:

```rust
impl Error {
    pub fn caused<K: Into<ErrorKind>>(self, kind: K) -> Self {
        Error::with_chain(self, kind)
    }
}
```

Would a simple approach like that work for this?

**Comment by Yamakaky** [comment]
Do you want to try a PR?

**Comment by TedDriggs** [comment]
Since #141 was merged, should this be closed?

**Comment by golddranks** [comment]
Indeed! Thanks!
