### ISSUE TITLE
Allow sections to be defined in any order

### ISSUE THREAD

**Issue by brson** [brson/error-chain#41]
Today the sections have to be defined in a strict order. This is mostly just because it's easier to implement. It would be better if sections could appear in any order.

cc https://github.com/brson/error-chain/issues/38

**Comment by golddranks** [comment]
Sent you a PR!

**Comment by Yamakaky** [comment]
Fixed by https://github.com/brson/error-chain/commit/f7110f834fe48c3b2d2d825cf681837a255ed15e
