### ISSUE TITLE
error in links section

### ISSUE THREAD

**Issue by benaryorg** [brson/error-chain#65]
[Here](https://gist.github.com/a9f5c9324cf1ce9515d20ad2552835c7) is a minimal example, the real example is a bit larger.

Shouldn't this work?

**Comment by Yamakaky** [comment]
It does for me...

**Comment by benaryorg** [comment]
Clarification:
- cargo 0.13.0-nightly
- rustc 1.13.0
- error-chain 0.5.0

Error:

```text
error: no rules expected the token `;`
  --> src/main.rs
   |
14 |         error::Error, Lib;
   |                          ^
```

**Comment by benaryorg** [comment]
Same problems arise if I use apply [a patch](https://gist.github.com/e456b61f3b32231075b2d77fb38a8c2f) adding the types section to 090460a9aee6db2e055930e0548e21b226319a81 of https://github.com/cobalt-org/cobalt.rs:

```text
error: no rules expected the token `;`
 --> src/error.rs:9:33
  |
9 |         Error, ErrorKind, Result;
  |                                 ^

error: Could not compile `cobalt-bin`.
```

**Comment by Yamakaky** [comment]
Could you try with `master`?

**Comment by benaryorg** [comment]
`master` builds.

**Comment by Yamakaky** [comment]
Well, problem solved ^^

**Comment by benaryorg** [comment]
Is there an ETA for the next release? Using git in a project feels so wrong.…

**Comment by Yamakaky** [comment]
I know, I was waiting for a PR to be merged, but I think I'll do one now. I have to wait for @brson to do it, though...

**Comment by benaryorg** [comment]
> I think I'll do one now

That would be really awesome.

**Comment by Yamakaky** [comment]
Done!

**Comment by benaryorg** [comment]
Thanks! Working perfectly fine.

**Comment by Yamakaky** [comment]
Cool! If you have some time, you can help me update the doc and adding more examples ;)
