### ISSUE TITLE
Do not capture backtrace without RUST_BACKTRACE=1

### ISSUE THREAD

**Issue by pravic** [brson/error-chain#7]
Subj.

The problem described here: [rust-lang-nursery/rustup.rs#591](https://github.com/rust-lang-nursery/rustup.rs/issues/591). Guess issue related to this crate since backtrace-rs is explicit thing to deal with it.

**Comment by brson** [comment]
Thanks for filing this. I'm amenable to making this behavior an option at least, but I also want to figure out why you are seeing so much disk thrashing on windows - it shouldn't be *that* expensive to capture a backtrace. Many languages capture them for every exception, and that's a model I want to support, just having backtraces always available.

**Comment by pravic** [comment]
I'll answer in that issue better.

**Comment by pravic** [comment]
> Many languages capture them for every exception, and that's a model I want to support, just having backtraces always available.

We can use [RtlCaptureStackBackTrace](https://github.com/alexcrichton/backtrace-rs/blob/master/Cargo.toml#L52-L55), it does not require debug symbols to work.

**Comment by brson** [comment]
Let's just go ahead and do this. No backtraces unless `RUST_BACKTRACE` is set and not equal to "0".
