### ISSUE TITLE
Why does extract_backtrace return Option<Option<BT>> instead of Option<BT> ?

### ISSUE THREAD

**Issue by Arnavion** [brson/error-chain#72]
If underlying error has `None` backtrace for any reason, the chained error will not get backtrace either - `extract_backtrace` will return `Some(None)` so `State::backtrace` will be `None`, and cycle will repeat again.

It seems to me it would be better if it was just `Option<BT>`, and the impl returned just `e.state.backtrace.clone()`

**Comment by Yamakaky** [comment]
Yeah, it was that way so I kept it, but I should change it. Do you want to PR?
