### ISSUE TITLE
add minimum supported version to Travis 

### ISSUE THREAD

**Issue by cardoe** [brson/error-chain#80]
So I know a lot of people use the nightly and a lot of people always run the latest stable rust. But there's some of us out there that will get stuck on a stable release for a few months due complexities in build environments, breakages moving forward, etc.

For all my crates I try to include the following in `.travis-ci.yml` so that there's a minimum supported version:
```
rust:
- nightly
- beta
- stable
- 1.4.0
```

Its fine to raise that level up as needed but its helpful to ensure that a "stable" series (e.g. 0.6.x) remains compatible with the same version of Rust or if it needs to be bumped up people can understand how they need to update.

**Comment by Yamakaky** [comment]
Seems like the latest supported version is the 1.8. However, it uses a feature from the latest stable. https://travis-ci.org/brson/error-chain/jobs/180998245#L286-L306. The modification in `lib.rs` is easy, the one in `error_chain.rs` less easy.

**Comment by cardoe** [comment]
Thank you. No matter the version its a welcome addition for me.
