### ISSUE TITLE
Add helpers to implement main()

### ISSUE THREAD

**Issue by joshtriplett** [brson/error-chain#81]
https://brson.github.io/2016/11/30/starting-with-error-chain provides a great template for `main()`, delegating to a function that can return a `Result`.  And I agree that almost all `main()` functions should look like that.  So, I'd love to have some helper methods for that pattern, to avoid duplicating that code across every application using error-chain.

I'd suggest two helper methods: one that prints the error, causes, and possible backtrace, and one that calls that method and then `::std::process::exit(1)`.  The former would help for projects that run individual commands/requests and want to thoroughly report errors for each without exiting on failure; the latter would work for all simple command-line tools that want to exit if the top-level main-equivalent returns an error.

With the latter, the template main could look something like this:

```rust
fn main() {
    real_main().toplevel_unwrap();
}
```

**Comment by Yamakaky** [comment]
Something like https://play.rust-lang.org/?gist=f98139dcdd16cceb898731f0fe649a34&version=stable&backtrace=0?

**Comment by joshtriplett** [comment]
Wrapping the whole thing in a macro (which expects a closure as an argument) seems a little too magic to me.  I'd prefer a helper like the `toplevel_unwrap()` I suggested above, or at most, a macro that takes a function name (`chain_main!(real_main);`).

**Comment by Yamakaky** [comment]
Yeah, it's just that I was on play.rust-lang.org, which doesn't allow the use of other crates.
How would you implement it? A trait on Result?

**Comment by joshtriplett** [comment]
Right. error-chain already provides a trait on Result, so this would just add one method to it.

**Comment by Yamakaky** [comment]
In fact, not exactly: ResultExt is defined on `Result<T, E> where E: Error`, and not `E: ChainedError`.

**Comment by joshtriplett** [comment]
Good point; in the absence of some kind of specialization, that trait wouldn't work. But another trait could.
