### ISSUE TITLE
Implement ResultExt<T, ?> for Result<T, Box<std::error::Error + Send>>

### ISSUE THREAD

**Issue by Jascha-N** [brson/error-chain#85]
It is currently impossible to call `chain_err` on `Result`s that have a boxed `std::error::Error` trait-object as `Err` variant. Since the cause of an error-chain error is stored as a boxed trait-object anyway, it would be nice to have this functionality.

**Comment by Yamakaky** [comment]
Could you send a PR please?

**Comment by Yamakaky** [comment]
Closing for #152
