### ISSUE TITLE
Numerous tests don't set ResultExt in types{} correctly

### ISSUE THREAD

**Issue by Arnavion** [brson/error-chain#92]
There are many tests that have `types { Error, ErrorKind, Result }` instead of `types { Error, ErrorKind, ResultExt, Result }` and thus are actually defining the `ResultExt` trait's name to be `Result`.

- https://github.com/brson/error-chain/blob/a1a597055e97818d144459017cdc1c4f9ab59855/tests/tests.rs#L13
- https://github.com/brson/error-chain/blob/a1a597055e97818d144459017cdc1c4f9ab59855/tests/tests.rs#L178
- https://github.com/brson/error-chain/blob/a1a597055e97818d144459017cdc1c4f9ab59855/tests/tests.rs#L193
- https://github.com/brson/error-chain/blob/a1a597055e97818d144459017cdc1c4f9ab59855/tests/tests.rs#L380
- https://github.com/brson/error-chain/blob/a1a597055e97818d144459017cdc1c4f9ab59855/tests/tests.rs#L444

**Comment by Yamakaky** [comment]
Hum, we forgot to change them with the syntax rollback. Do you want to do it?
