### ISSUE TITLE
Implement Eq on ErrorKind?

### ISSUE THREAD

**Issue by sourcefrog** [brson/error-chain#95]
I might be holding this wrong, but I'd like to write eg

    assert_eq!(*af.last_band_id().unwrap_err().kind(), ErrorKind::ArchiveEmpty);

this complains

    error[E0369]: binary operation `==` cannot be applied to type `errors::ErrorKind

Is that feasible to add?  Or could we add to the documentation some example of the intended way to write this?

I see I can use a destructuring match but that seems a little unnatural in a test.

**Comment by colin-kiegel** [comment]
I guess a `#[derive(PartialEq)]` should do the trick here: https://github.com/brson/error-chain/blob/62b3c0d1014d4a5b9af142be481f1eaf2b443c3d/src/error_chain.rs#L196-L197

**Comment by Yamakaky** [comment]
That would be a good idea, but that's not practical. [io::Error](https://doc.rust-lang.org/std/io/struct.Error.html), a very common error type, doesn't implement `Eq`, so auto-deriving would generate a compile time error which is not fixable by the end-user.
Since ErrorKind is generated, you can always manually implement `Eq`. Not ideal, but it works.

**Comment by sourcefrog** [comment]
Is there a particular recommended way to check the `.kind()` or should I use `match`?

**Comment by Yamakaky** [comment]
I think a match over ErrorKind is fine. If you also want to implement Eq on Error, you may want to pay attention to the backtrace and the error chain.

**Comment by sourcefrog** [comment]
ok thanks

**Comment by Yamakaky** [comment]
With https://github.com/Arnavion/derive-error-chain/ we may be able to derive Eq if possible.

**Comment by mikeycgto** [comment]
I wrote a small macro to assert against the error types that are returned by library. Not sure if this will be useful to anyone else but I figured I would share :)

```rust
// usage:
//    assert_error_kind!(some_err, ErrorKind::MyErrorType)
macro_rules! assert_error_kind {
    ($err:expr, $kind:pat) => (match *$err.kind() {
        $kind => assert!(true, "{:?} is of kind {:?}", $err, stringify!($kind)),
        _     => assert!(false, "{:?} is NOT of kind {:?}", $err, stringify!($kind))
    });
}

```
