### ISSUE TITLE
Cannot document "links" error kinds

### ISSUE THREAD

**Issue by mathstuf** [brson/error-chain#96]
Docstrings are allowed in the `errors` block, but I I've just been getting errors for those inside the `links` block, leaving me with `missing_docs` warnings. It'd be great if the macro supported documenting these variants.

**Comment by Yamakaky** [comment]
It does: https://github.com/brson/error-chain/blob/master/examples/doc.rs#L16. See https://github.com/brson/error-chain/issues/63 for more details about why we can't use `///`.

**Comment by mathstuf** [comment]
OK, thanks. Closing as a duplicate then.

**Comment by DenisKolodin** [comment]
If you get here and don't want to search more the workaround is:
```rust
error_chain! {
    foreign_links {
        Json(::serde_json::Error) #[doc = "Json error"];
    }
    errors {
        /// Rpc error,
        Rpc(e: ::serde_json::Value) {
            description("rpc error")
            display("rpc error: '{}'", e)
        }
    }
}
```
Found here: https://github.com/brson/error-chain/issues/61
