### ISSUE TITLE
Implement ResultExt<T, ...> for Result<T, E> where E: Error

### ISSUE THREAD

**Issue by dlight** [brson/error-chain#99]
So that one can use `?` instead of calling `chain_err` on foreign errors without first registering them with `foreign_links!`.

Requires specialization to still dispatch the foreign links as before (and to be possible to implement #85 as well).

Rationale: to avoid boilerplate when writing short Rust programs (the kind of programs that would be calling `unwrap` before error-chain). Of course foreign links or better, `chain_err`, is preferable on more structured programs.

**Comment by Yamakaky** [comment]
I don't see what you mean, `ResultExt` would not llow to use `?`. What would you add as `ErrorKind`?

**Comment by dlight** [comment]
Perhaps add a new variant `OtherForeignError(Box<Error>)`?

**Comment by joshtriplett** [comment]
I actually consider it a feature that when I attempt to use `try!` or `?` on a new error type, I have to add that to the `error_chain!` invocation. Having that transparently become an `OtherForeignError` would prevent me from noticing that I might want to add a new variant.

**Comment by Yamakaky** [comment]
Hum, not sure it would work well with the From implementations.

**Comment by Yamakaky** [comment]
Closing for #152
